### ISSUE TITLE
Request ARM/64 supports

### ISSUE THREAD

**Issue by wherewhere** [lowleveldesign/detours-win32metadata#1]
It only has x86/x64 libraries. Could you add ARM and ARM64 libraries into the nuget?

**Comment by lowleveldesign** [comment]
The latest version (4.0.1.15) should contain arm binaries.

**Comment by wherewhere** [comment]
![😞](https://github.com/ashmind/SharpLab/assets/27689196/88f4865c-3d38-47b5-878e-d43aaf77096e)
![image](https://github.com/lowleveldesign/detours-win32metadata/assets/27689196/6f28f84f-9714-4d1f-a5d8-aefdc2ec73e3)

**Comment by lowleveldesign** [comment]
That's .gitignore - the nuget package contains the ARM binaries in it.

**Comment by wherewhere** [comment]
I mean that I am going to make a contribution but you have finished 🤣.

**Comment by lowleveldesign** [comment]
Well, you still made a valuable PR (additionally fixing a bug for x64). Great thanks!
