### ISSUE TITLE
Request detours.h in nuget package

### ISSUE THREAD

**Issue by wherewhere** [lowleveldesign/detours-win32metadata#3]
Add `detours.h` into nuget package so that we can use it in C++ projects directly.
(Because I don't know how to use original method after hook it in .NET 😂...

**Comment by lowleveldesign** [comment]
Hey, adding include file is probably not enough, as the native Nuget package requires a different folder structure (build/native) and (probably) a .targets file. Another thing is that C++ developers were not my intended audience. I personally preferred to use vcpkg when developing in C++. However, if you think it's worth the effort and have time to adopt this package to work for both managed and native audience, feel free to prepare a PR. Thanks

**Comment by lowleveldesign** [comment]
Ah, and I plan to soon publish a video showing how I use this package to prepare a hook in C#. So stay tuned :)

**Comment by wherewhere** [comment]
You can add .h to the root of package and add a target file with other name. Then we can add the nuget and add the target by self.
https://github.com/wherewhere/CoreAppUWP/blob/muxc/CoreAppUWP.WinRT/CoreAppUWP.WinRT.vcxproj#L97-L100
